/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2021-05-17 02:54:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import controller.*;
import model.*;

public final class menuInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("controller");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>Menu Insert</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t\tbody{\r\n");
      out.write("\t\t\t\t\t\tbackground-image: url(../img/背景.jpg) ;\r\n");
      out.write("\t\t\t\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\t\t\t\tbackground-attachment: fixed;\r\n");
      out.write("\t\t\t\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\ttable{margin:auto;}\r\n");
      out.write("\t\t\t\tcaption{color:#0a0a0a;font-size:20pt;}\r\n");
      out.write("\t\t\t\tth{text-align:left;background:#A4FFDB;color:#007B66;}\r\n");
      out.write("\t\t\t\ttd{background:#E3FFE3;}\r\n");
      out.write("\t\t\t\tth#bottom{text-align:center;}\r\n");
      out.write("\t\t\t\tp{text-align:center;}\r\n");
      out.write("\t\t\t\ta{color: #ffd700;}\r\n");
      out.write("\t\t\t\th1 {\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t</style>\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t\tfunction dataCheck(obj){\r\n");
      out.write("\t\t\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\t\t\tif(obj.menuName.value.length < 1){\r\n");
      out.write("\t\t\t\t\t\tmsg += \"メニュー名を入力してください。\\n\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(!obj.price.value.match(/^[0-9]+$/g)){\r\n");
      out.write("\t\t\t\t\t\tmsg += \"価格を数値で入力してください。\\n\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar i;\r\n");
      out.write("\t\t\t\t\tfor(i = 0 ; i < obj.orderFlg.length ; i++){\r\n");
      out.write("\t\t\t\t\t\tif(obj.orderFlg[i].checked){\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(i >= obj.orderFlg.length){\r\n");
      out.write("\t\t\t\t\t\tmsg += \"オーダーの可否をチェックしてください\\n\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(msg.length > 0){\r\n");
      out.write("\t\t\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t//-->\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url(./img/背景.jpg); background-size: cover\">\r\n");

			int typeId;
			try{
				typeId = Integer.parseInt(request.getParameter("typeId"));
			}catch(NumberFormatException e){
				typeId = 200;
			}
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		request.setCharacterEncoding("UTF-8");
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      model.Admin adminInfo = null;
      synchronized (session) {
        adminInfo = (model.Admin) _jspx_page_context.getAttribute("adminInfo", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (adminInfo == null){
          adminInfo = new model.Admin();
          _jspx_page_context.setAttribute("adminInfo", adminInfo, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

		IdealException msg = (IdealException) request.getAttribute("msg");
		if (msg != null) {
	
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
      out.print(msg.getMsg());
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		}
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      java.util.ArrayList mType = null;
      mType = (java.util.ArrayList) _jspx_page_context.getAttribute("mType", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (mType == null){
        mType = new java.util.ArrayList();
        _jspx_page_context.setAttribute("mType", mType, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      java.util.ArrayList menu = null;
      menu = (java.util.ArrayList) _jspx_page_context.getAttribute("menu", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (menu == null){
        menu = new java.util.ArrayList();
        _jspx_page_context.setAttribute("menu", menu, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\t<table border>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action = \"MenuOperationSvl\" method = \"post\" onSubmit = \"return dataCheck(this);\">\r\n");
      out.write("\t\t\t\t<h1>メニューの追加</h1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>メニュー名</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"menuName\" size=\"30\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>価格</th>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\" name = \"price\" size = \"6\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>オーダー可</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type = \"radio\" name = \"orderFlg\" value = \"1\"/>可\r\n");
      out.write("\t\t\t\t\t\t<input type = \"radio\" name = \"orderFlg\" value = \"0\"/>不可\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>分類</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name = \"typeId\">\r\n");
      out.write("\t\t\t\t\t\t");
  for(Object o : mType){
							MenuType mt = (MenuType)o;
							String selected = "";
							if(mt.getTypeId()>=200){
							if(typeId == mt.getTypeId()){
								selected = "selected";
							}else{
								selected = "";
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print( ((MenuType)o).getTypeId() );
      out.write('"');
      out.write(' ');
      out.print( selected );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( ((MenuType)o).getTypeName() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t");
	}
						}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>コメント</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<textarea name = \"detail\" cols = \"30\" rows = \"4\"></textarea>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"mode\" value =\"");
      out.print( MenuOperationSvl.INSERT );
      out.write("\" />\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan = \"2\" id = \"bottom\"><input type = \"submit\" value = \"メニューを追加\"/></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<p><a href = \"MenuMaintenanceSvl?typeId=");
      out.print(typeId );
      out.write("\">一覧表示画面へ戻る</a></p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
