/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2021-05-09 09:26:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import model.*;
import controller.*;

public final class showMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("controller");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 System.out.println("showmenu0"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>メニュー紹介</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"showMenu.css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\t\t\t\t//1.メニュー名クリック時のコメント表示、\r\n");
      out.write("\t\t\t\tfunction showDetail(id){\r\n");
      out.write("\t\t\t\t\t//1.引き渡されたメニュー番号の\"style.display\"が\"block\"の時、\r\n");
      out.write("\t\t\t\t\tif(document.getElementById(id).style.display == 'block'){\r\n");
      out.write("\t\t\t\t\t\t//1.引き渡されたメニュー番号の\"style.display\"を\"none\"に設定する。\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(id).style.display = 'none';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//2.引き渡されたメニュー番号の\"style.display\"が\"block\"以外の時、\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t//1.引き渡されたメニュー番号の\"style.display\"を\"block\"に設定する。\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(id).style.display = 'block';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//2.メニュー名クリック時のメニュー名のフォント変更、\r\n");
      out.write("\t\t\t\tfunction change(id,val){\r\n");
      out.write("\t\t\t\t\t//1.引き渡された色区分(val)が\"0\"の時\r\n");
      out.write("\t\t\t\t\tif(val == 0){\r\n");
      out.write("\t\t\t\t\t\t//1.引き渡されたメニュー番号のフォント色を\"red\"、フォントの太さを\"bold\"に設定する。\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(id).style.color = 'red';\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(id).style.fontWeight = 'bold';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//2.引き渡された色区分(val)が\"0\"以外の時\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t//1.引き渡されたメニュー番号のフォント色を\"DarkOliveGreen\"、フォントの太さを\"normal\"に設定する。\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(id).style.color = 'DarkOliveGreen';\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(id).style.fontWeight = 'normal';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t//-->\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 System.out.println("showmenu start"); 
      out.write('\r');
      out.write('\n');
      java.util.ArrayList courseList = null;
      courseList = (java.util.ArrayList) _jspx_page_context.getAttribute("courseList", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (courseList == null){
        courseList = new java.util.ArrayList();
        _jspx_page_context.setAttribute("courseList", courseList, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.ArrayList menuList = null;
      menuList = (java.util.ArrayList) _jspx_page_context.getAttribute("menuList", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (menuList == null){
        menuList = new java.util.ArrayList();
        _jspx_page_context.setAttribute("menuList", menuList, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.ArrayList mtype = null;
      mtype = (java.util.ArrayList) _jspx_page_context.getAttribute("mtype", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (mtype == null){
        mtype = new java.util.ArrayList();
        _jspx_page_context.setAttribute("mtype", mtype, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

		//通貨フォーマット
		NumberFormat cf = NumberFormat.getCurrencyInstance(new Locale("ja",
				"JP"));
	
      out.write("\r\n");
      out.write("\t<h1>メニュー紹介</h1>\r\n");
      out.write("\t<br />\r\n");
      out.write("\r\n");
      out.write("\t<table cellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td id=\"title\" colspan=\"2\">■コース料理<br /> <br />\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			ArrayList<Course> al = Course.getOneCourseList();
		  	for(int i = 0; i < al.size() ; i++) {
		  		Course c = al.get(i);
		
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td id=\"courseMenu\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( c.getCourseName() );
      out.write('\r');
      out.write('\n');
 System.out.println("1" + c.getCourseName()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"courseDetail\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( c.getDetail() );
      out.write('\r');
      out.write('\n');
 System.out.println("2" + c.getDetail()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td id=\"coursePrice\"> &yen;\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( c.getPrice() );
      out.write('\r');
      out.write('\n');
 System.out.println("3" + c.getPrice()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
 for(int j = 0; j < courseList.size(); j++){
								Course cc = (Course)courseList.get(j);
									if(cc.getCourseId() == c.getCourseId()) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"subMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"subMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( cc.getMenuName() );
      out.write('\r');
      out.write('\n');
 System.out.println("4" + cc.getMenuName()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td id=\"title\" colspan=\"2\">■一品料理</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

			ArrayList<Menu> me = Menu.getMenuList();
			for(int j = 1; j < mtype.size(); j++) {
				MenuType mt = (MenuType)mtype.get(j);
			
      out.write("\r\n");
      out.write("\t\t\t<tr id=\"type\">\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" id=\"type\">\r\n");
      out.write("\t\t\t\t\t<div id=\"type\">");
      out.print( mt.getTypeName() );
      out.write("</div>\r\n");
 System.out.println("1"+mt.getTypeName()); 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				for(int i = 0; i < me.size(); i++){
					Menu m = me.get(i);
					if(m.getTypeId() == mt.getTypeId()) {
						if(m.getDetail() != null){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"menu\" id=\"menu");
      out.print( i );
      out.write("\" onMouseOver=\"change('menu");
      out.print( i );
      out.write("',0);\"\r\n");
      out.write("\t\t\t\t\t\t\tonMouseOut=\"change('menu");
      out.print( i );
      out.write("',1);\" onClick=\"showDetail('");
      out.print( i );
      out.write("')\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( m.getMenuName() );
      out.write("</div>\r\n");
 System.out.println("2"+ m.getMenuName()); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"exp\" id=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( m.getDetail() );
      out.write("</div>\r\n");
 System.out.println("3" + m.getDetail()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"price\">");
      out.print( cf.format(m.getPrice()));
      out.write("</td>\r\n");
 System.out.println("4" +cf.format(m.getPrice()));  
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"menu\">\r\n");
      out.write("\t\t\t\t\t<div class=\"menu\" >");
      out.print( m.getMenuName() );
      out.write("</div>\r\n");
 System.out.println("2"+ m.getMenuName()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"price\">");
      out.print( cf.format(m.getPrice()));
      out.write("</td>\r\n");
 System.out.println("4" +cf.format(m.getPrice()));  
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t");
if(session.getAttribute("userInfo") != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"userIndex.jsp\">[戻る]</a>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"home.jsp\">[戻る]</a>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
