/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2021-05-16 03:04:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>お客様情報登録</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"meisai.css\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/JavaScript\" src=\"incScript.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/JavaScript\">\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t\t//1.入力項目チェック\r\n");
      out.write("\t\t\t\tfunction checkData(obj){\r\n");
      out.write("\t\t\t\t\t//1.メッセージを宣言\r\n");
      out.write("\t\t\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\t\t\t//2.名前が未入力の時、\r\n");
      out.write("\t\t\t\t\tif(obj.usrName.value == null || obj.usrName.value == \"\"){\r\n");
      out.write("\t\t\t\t\t\t//1.メッセージに\"お名前を入力してください！\\n\"を追加\r\n");
      out.write("\t\t\t\t\t\tmsg += \"お名前を入力してください！\\n\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//7.パスワードが未入力の時、\r\n");
      out.write("\t\t\t\t\tif(obj.password.value == null || obj.password.value == \"\"){\r\n");
      out.write("\t\t\t\t\t\t//1.メッセージに\"パスワードを入力してください。\\n\"を追加\r\n");
      out.write("\t\t\t\t\t\tmsg += \"パスワードを入力してください。\\n\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//8.メッセージが空白の時、\r\n");
      out.write("\t\t\t\t\tif(msg == \"\"){\r\n");
      out.write("\t\t\t\t\t\t//1.\"true\"を返す。\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t//9.メッセージが空白以外の時、\r\n");
      out.write("\t\t\t\t\t\t//1.アラーとでメッセージを表示し\"false\"を返す。\r\n");
      out.write("\t\t\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t//-->\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>お客様情報登録</h2>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"UserOperationSvl\" onsubmit=\"return checkData(this)\" method=\"post\">\r\n");
      out.write("\t\t\t<table border>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>※お名前</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"usrName\" size=\"30\" maxlength=\"30\" style=\"ime-mode: active;\" value=\"\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>住 所</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"address\" size=\"50\" maxlength=\"200\" style=\"ime-mode: active;\" value=\"\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>電話番号</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"phone\" size=\"15\" maxlength=\"20\" style=\"ime-mode: disabled;\" value=\"\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>e-mail</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"mail\" size=\"30\" maxlength=\"100\" style=\"ime-mode: disabled;\" value=\"\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>パスワード※</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"password\" size=\"8\" maxlength=\"8\" style=\"ime-mode: inactive;\" value=\"\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"mode\" value = \"11\" />\r\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"mailMode\" value = \"123\" />\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td id=\"sub\" colspan=\"2\">※は必修入力です。\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\" 登録 \" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\t\t<p id=\"boder\"><a href=\"home.jsp\">ホームページに戻る</a></p>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
